### 해리스 특징점 검출

In [1]:
#입력 영상 생성
import cv2 as cv
import numpy as np

img = np.array([[0,0,0,0,0,0,0,0,0,0],
                [0,0,0,0,0,0,0,0,0,0],
                [0,0,0,1,0,0,0,0,0,0],
                [0,0,0,1,1,0,0,0,0,0],
                [0,0,0,1,1,1,0,0,0,0],
                [0,0,0,1,1,1,1,0,0,0],
                [0,0,0,0,0,0,0,0,0,0],
                [0,0,0,0,0,0,0,0,0,0],
                [0,0,0,0,0,0,0,0,0,0]], dtype = np.float32)

In [2]:
#필터 생성 및 미분 값과 맵 C 계산
ux = np.array([[-1,0,1]])
uy = np.array([-1,0,1]).transpose()
k = cv.getGaussianKernel(3,1)
g = np.outer(k, k.transpose())

dy = cv.filter2D(img, cv.CV_32F, uy)
dx = cv.filter2D(img, cv.CV_32F, ux)
dyy = dy*dy
dxx = dx*dx
dyx = dy*dx
gdyy = cv.filter2D(dyy, cv.CV_32F, g)
gdxx = cv.filter2D(dxx, cv.CV_32F, g)
gdyx = cv.filter2D(dyx, cv.CV_32F, g)
C = (gdyy*gdxx-gdyx*gdyx) - 0.04*(gdyy+gdxx)*(gdyy+gdxx)

In [3]:
#비최대 억제 적용 및 영상 출력
for j in range(1, C.shape[0]-1):
    for i in range(1, C.shape[1]-1):
        if C[j,i]>0.1 and sum(sum(C[j,i]>C[j-1:j+2,i-1:i+2]))==8:
            img[j,i]=9
np.set_printoptions(precision=2)
print(dy)
print(dx)
print(dyy)
print(dxx)
print(dyx)
print(gdyy)
print(gdxx)
print(gdyx)
print(C)
print(img)

popping = np.zeros([160,160], np.uint8)
for j in range(0,160):
    for i in range(0,160):
        popping[j,i]=np.uint8((C[j//25,i//25]+0.06)*700)

cv.imshow('Image Display', popping)
cv.waitKey()
cv.destroyAllWindows()

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  1.  0.  0.  0.]
 [ 0.  0.  0. -1. -1. -1.  0.  0.  0.  0.]
 [ 0.  0.  0. -1. -1. -1. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  1. -1. -1.  0.  0.  0.  0.]
 [ 0.  0.  1.  1.  0. -1. -1.  0.  0.  0.]
 [ 0.  0.  1.  1.  0.  0. -1. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0. 

### SIFT 검출과 기술자 추출

In [4]:
import cv2 as cv

img = cv.imread('mot_color70.jpg')
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

sift = cv.SIFT_create()
kp, des = sift.detectAndCompute(gray, None)

gray = cv.drawKeypoints(gray, kp, None, flags = cv.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
cv.imshow('sift', gray)

k = cv.waitKey()
cv.destroyAllWindows()

In [5]:
import cv2 as cv

img = cv.imread('mot_color70.jpg')
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

sift = cv.SIFT_create(nfeatures=0, nOctaveLayers=3, contrastThreshold=0.04,
                     edgeThreshold=10, sigma=1.6)
kp, des = sift.detectAndCompute(gray, None)

gray = cv.drawKeypoints(gray, kp, None, flags = cv.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
cv.imshow('sift', gray)

k = cv.waitKey()
cv.destroyAllWindows()

In [6]:
import cv2 as cv

img = cv.imread('mot_color70.jpg')
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

sift = cv.SIFT_create(nfeatures=0, nOctaveLayers=3, contrastThreshold=0.04,
                     edgeThreshold=10, sigma=1.6)
kp = sift.detect(gray, None)
des = sift.compute(gray,kp)

gray = cv.drawKeypoints(gray, kp, None, flags = cv.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
cv.imshow('sift', gray)

k = cv.waitKey()
cv.destroyAllWindows()

### SURF 알고리즘

In [7]:
photo = cv.imread('mot_color70.jpg')
#SURF 알고리즘 객체 생성
feature = cv.xfeatures2d.SURF_create(500)
#각 이미지에서 키포인트 추출
keyPoint01, descriptors01 = feature.detectAndCompute(photo01, None)
keyPoint02, descriptors02 = feature.detectAndCompute(photo02, None)

#Brute-force 방식으로 매칭
matcher = cv.BFMatcher(cv2.NORM_L1, True)
matches = matcher.match(descriptors01, descriptors02)

#키포인트 및 매칭 결과를 이미지에 그리기
keyPointImage01 = cv.drawKeypoints(photo, keyPoint1, None, None, cv.DRAW_MATCHES_FLAGS_DEFAULT)
keyPointImage02 = cv.drawKeypoints(photo, keyPoint2, None, None, cv.DRAW_MATCHES_FLAGS_DEFAULT)
matchImage = cv.drawMatches(photo, keyPoint01, photo, keyPoint02, matches, None)

cv.imshow("keyPoint Image 01", keyPointImage01)
cv.imshow("keyPoint Image 02", keyPointImage02)
cv.imshow("match Image", matchImage)
cv.waitKey(0)

AttributeError: module 'cv2' has no attribute 'xfeatures2d'

### FLANN 라이브러리를 이용한 SIFT 매칭

In [8]:
import cv2 as cv
import numpy as np
import time

img1 = cv.imread('mot_color70.jpg')[190:350, 440:560]
gray1 = cv.cvtColor(img1, cv.COLOR_BGR2GRAY)
img2 = cv.imread('mot_color83.jpg')
gray2 = cv.cvtColor(img2, cv.COLOR_BGR2GRAY)

sift = cv.SIFT_create()
kp1, des1 = sift.detectAndCompute(gray1, None)
kp2, des2 = sift.detectAndCompute(gray2, None)
print('특징점 개수:', len(kp1), len(kp2))

start = time.time()
flann_matcher = cv.DescriptorMatcher_create(cv.DescriptorMatcher_FLANNBASED)
knn_match = flann_matcher.knnMatch(des1, des2,2)

T = 0.7
good_match = []
for nearest1, nearest2 in knn_match:
    if (nearest1.distance/nearest2.distance)<T:
        good_match.append(nearest1)
print('매칭에 걸린 시간:', time.time()-start)

img_match = np.empty((max(img1.shape[0], img2.shape[0]), img1.shape[1]+img2.shape[1],3),dtype=np.uint8)
cv.drawMatches(img1, kp1, img2, kp2, good_match, img_match, flags = cv.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)

cv.imshow('Good Matches', img_match)

k = cv.waitKey()
cv.destroyAllWindows()

특징점 개수: 231 4096
매칭에 걸린 시간: 0.05569958686828613


In [12]:
!pip install --upgrade opencv-python

   ---------------------------------------- 0.0/38.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/38.6 MB 1.7 MB/s eta 0:00:23
    --------------------------------------- 0.5/38.6 MB 5.6 MB/s eta 0:00:07
   - -------------------------------------- 1.1/38.6 MB 7.9 MB/s eta 0:00:05
   - -------------------------------------- 1.9/38.6 MB 9.8 MB/s eta 0:00:04
   -- ------------------------------------- 2.8/38.6 MB 11.8 MB/s eta 0:00:04
   ---- ----------------------------------- 4.0/38.6 MB 14.1 MB/s eta 0:00:03
   ----- ---------------------------------- 5.6/38.6 MB 16.9 MB/s eta 0:00:02
   ------- -------------------------------- 7.5/38.6 MB 19.9 MB/s eta 0:00:02
   --------- ------------------------------ 9.6/38.6 MB 22.7 MB/s eta 0:00:02
   ------------- -------------------------- 12.9/38.6 MB 43.7 MB/s eta 0:00:01
   ---------------- ----------------------- 15.7/38.6 MB 54.4 MB/s eta 0:00:01
   -

  You can safely remove it manually.


In [13]:
!pip install opencv-contrib-python

  Using cached opencv_contrib_python-4.9.0.80-cp37-abi3-win_amd64.whl.metadata (20 kB)
Using cached opencv_contrib_python-4.9.0.80-cp37-abi3-win_amd64.whl (45.3 MB)


### FAISS 라이브러리

In [14]:
img1 = cv.imread('mot_color70.jpg')[190:350, 440:560]
img2 = cv.imread('mot_color83.jpg')
gray1 = cv.cvtColor(img1, cv.COLOR_BGR2GRAY)
gray2 = cv.cvtColor(img2, cv.COLOR_BGR2GRAY)

# SIFT 생성
detector = cv.xfeatures2d.SIFT_create()
# 키 포인트와 서술자 추출
kp1, desc1 = detector.detectAndCompute(gray1, None)
kp2, desc2 = detector.detectAndCompute(gray2, None)

# 인덱스 파라미터와 검색 파라미터 설정 ---①
FLANN_INDEX_KDTREE = 1
index_params = dict(algorithm=FLANN_INDEX_KDTREE, trees=5)
search_params = dict(checks=50)

# Flann 매처 생성 ---③
matcher = cv.FlannBasedMatcher(index_params, search_params)
# 매칭 계산 ---④
matches = matcher.match(desc1, desc2)
# 매칭 그리기
res = cv.drawMatches(img1, kp1, img2, kp2, matches, None, \
                flags=cv2.DRAW_MATCHES_FLAGS_NOT_DRAW_SINGLE_POINTS)

cv2.imshow('Flann + SIFT', res)
cv2.waitKey()
cv2.destroyAllWindows()

AttributeError: module 'cv2' has no attribute 'xfeatures2d'

In [16]:
img1 = cv.imread('mot_color70.jpg')[190:350, 440:560]
img2 = cv.imread('mot_color83.jpg')
gray1 = cv.cvtColor(img1, cv.COLOR_BGR2GRAY)
gray2 = cv.cvtColor(img2, cv.COLOR_BGR2GRAY)

# SIFT 생성
detector = cv.xfeatures2d.SIFT_create()
# 키 포인트와 서술자 추출
kp1, desc1 = detector.detectAndCompute(gray1, None)
kp2, desc2 = detector.detectAndCompute(gray2, None)

sift = cv.SIFT_create()
kp1, des1 = sift.detectAndCompute(gray1, None)
kp2, des2 = sift.detectAndCompute(gray2, None)

start = time.time()
flann_matcher = cv.DescriptorMatcher_create(cv.DescriptorMatcher_FLANNBASED)
knn_match = flann_matcher.knnMatch(des1, des2,2)

T = 0.7
good_match = []
for nearest1, nearest2 in knn_match:
    if (nearest1.distance/nearest2.distance)<T:
        good_match.append(nearest1)

points1 = np.float32([kp1[gm.queryIdx].pt for gm in good_match])
points2 = np.float32([kp2[gm.queryIdx].pt for gm in good_match])
H, _ = cv.findHomograpy(points1, points2, cv.RANSAC)

h1, w1 = img1.shape[0], img1.shape[1]
h2, w2 = img2.shape[0], img2.shape[1]

box1 = np.float32([[0,0], [0,h1-1], [w1-1, h1-1], [w1-1,0]]).reshape(4,1,2)
box2 = cv.perspectiveTransform(box1, H)

img2 = cv.polylines(img2, [np.int32(box2)], True, (0,255,0), 8)

img_match = np.empty((max(h1,h2), w1+w2, 3), dtype=np.uint8)
cv.drawMatches(img1, kp1, img2, kp2, good_match, img_match, flags = cv.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)

cv.imshow('Matches and Homography', img_match)

k = cv.waitKey()
cv.destroyAllWindows()

AttributeError: module 'cv2' has no attribute 'xfeatures2d'